phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install pytest  # Ensure pytest is installed
  pre_build:
    commands:
      - echo "Running tests..."
      - pytest tests/
