version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt  # Install required packages

  pre_build:
    commands:
      - echo "Checking project structure..."
      - ls -R
      - pytest tests/                     # Run unit tests

  build:
    commands:
      - echo "Build phase complete!"

artifacts:
  files:
    - '**/*'  # Include all files in the build artifacts
